version: '3.8'

services:
  bot-pendientes:
    # Opción 1: Build local (desarrollo)
    build:
      context: .
      dockerfile: Dockerfile
    
    # Opción 2: Usar imagen desde GHCR (producción)
    # Descomenta la siguiente línea y comenta el 'build' para usar GHCR
    # image: ghcr.io/tu-usuario/bot-pendientes:latest
    
    image: bot-pendientes:latest
    container_name: telegram-todo-bot
    restart: unless-stopped
    
    # Variables de entorno (usar archivo .env)
    env_file:
      - .env
    
    # Volúmenes para persistir logs
    volumes:
      - ./logs:/app/logs:rw
    
    # Configuración de logging
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    
    # Recursos del contenedor
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    
    # Red personalizada (opcional)
    networks:
      - bot-network

# Red personalizada
networks:
  bot-network:
    driver: bridge

# Volúmenes nombrados (opcional para logs persistentes)
volumes:
  bot-logs:
    driver: local
